version: '2.1'
services:
  orders:
    image: orders
    hostname: orders
    ports:
    - "8080:8080"
    networks:
      - app_net
    depends_on:
    - kafka
    - products

  products:
    image: products
    hostname: products
    ports:
    - "8081:8080"
    networks:
      - app_net
    depends_on:
    - kafka

  zoo:
    image: zookeeper:3.4.9
    restart: unless-stopped
    hostname: zoo
    ports:
    - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo:2888:3888
    networks:
      - app_net
    #volumes:
    # - ./data/zoo/data:/data
    # - ./data/zoo/datalog:/datalog


  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    ports:
    - "9092:9092"
    - "19092:19092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #volumes:
    #- ./data/kafka/data:/var/lib/kafka/data
    networks:
      - app_net
    depends_on:
    - zoo

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    hostname: kafka-schema-registry
    ports:
    - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - app_net
    depends_on:
    - zoo
    - kafka

  schema-registry-ui:
    image: landoop/schema-registry-ui:0.9.4
    hostname: kafka-schema-registry-ui
    ports:
    - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: http://kafka-schema-registry:8081/
      PROXY: "true"
    networks:
      - app_net
    depends_on:
    - kafka-schema-registry

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.0.0
    hostname: kafka-rest-proxy
    ports:
    - "8082:8082"
    environment:
      # KAFKA_REST_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
    networks:
      - app_net
    depends_on:
    - zoo
    - kafka
    - kafka-schema-registry

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    hostname: kafka-topics-ui
    ports:
    - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    networks:
      - app_net
    depends_on:
    - zoo
    - kafka
    - kafka-schema-registry
    - kafka-rest-proxy

  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.0.0
    hostname: kafka-connect
    ports:
    - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:19092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://kafka-schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://kafka-schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
    networks:
      - app_net
    depends_on:
    - zoo
    - kafka
    - kafka-schema-registry
    - kafka-rest-proxy

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.4
    hostname: kafka-connect-ui
    ports:
    - "8003:8000"
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    networks:
      - app_net
    depends_on:
    - kafka-connect

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:0.4.0
    ports:
    - "8004:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    networks:
      - app_net
    links:
    - zoonavigator-api
    depends_on:
    - zoonavigator-api

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:0.4.0
    environment:
      SERVER_HTTP_PORT: 9000
    networks:
      - app_net
    depends_on:
    - zoo

networks:
  app_net:
    name: app_net
